<script setup lang="ts">
import { computed } from 'vue'
import type { AdminGame, GamePlayer } from '@@/types/admin-club'
definePageMeta({ allowedRoles: ['admin'] })
type PlayerDetail = { player: { full_name: string, shirt_number: number | null, team: { name: string, age_group: { name: string } } }, games: Array<{ game: AdminGame, record: GamePlayer }> }
const id = useRoute().params.id as string
const { data, pending } = await useFetch<PlayerDetail>(`/api/admin/players/${id}`)
const games = computed(() => data.value?.games ?? [])
const totals = computed(() => games.value.reduce((sum, item) => ({ minutes: sum.minutes + item.record.minutes_played, goals: sum.goals + item.record.goals, assists: sum.assists + item.record.assists, yellow: sum.yellow + item.record.yellow_cards, red: sum.red + item.record.red_cards }), { minutes: 0, goals: 0, assists: 0, yellow: 0, red: 0 }))
function format(value: string) { return new Intl.DateTimeFormat('en-GB', { dateStyle: 'medium' }).format(new Date(value)) }
</script>
<template><div class="mx-auto max-w-4xl space-y-6"><NuxtLink to="/admin/players" class="text-sm text-brand-700">← Players</NuxtLink><div v-if="pending">Loading player...</div><template v-else-if="data"><div><h1>{{ data.player.full_name }}{{ data.player.shirt_number ? ` · #${data.player.shirt_number}` : '' }}</h1><p class="text-body text-[color:var(--color-text-secondary)]">{{ data.player.team.name }} · {{ data.player.team.age_group.name }}</p></div><div class="grid gap-3 grid-cols-2 sm:grid-cols-5"><Card v-for="item in [{ label: 'Games', value: games.length }, { label: 'Minutes', value: totals.minutes }, { label: 'Goals', value: totals.goals }, { label: 'Assists', value: totals.assists }, { label: 'Cards', value: `${totals.yellow}/${totals.red}` }]" :key="item.label"><p class="text-label text-[color:var(--color-text-secondary)]">{{ item.label }}</p><p class="mt-1 text-h2">{{ item.value }}</p></Card></div><Card class="overflow-hidden p-0"><div class="border-b border-border p-4"><h2>Game history</h2></div><p v-if="!games.length" class="p-6 text-center text-sm text-[color:var(--color-text-secondary)]">No game records yet.</p><NuxtLink v-for="item in games" :key="item.game.id" :to="`/admin/games/${item.game.id}`" class="block border-b border-border p-4 last:border-b-0 hover:bg-brand-50/50"><div class="flex justify-between gap-3"><p class="font-medium">{{ item.game.team.name }} vs {{ item.game.opponent_name }}</p><p>{{ item.record.goals }}G · {{ item.record.assists }}A</p></div><p class="mt-1 text-sm text-[color:var(--color-text-secondary)]">{{ format(item.game.scheduled_at) }} · {{ item.record.minutes_played }} min · {{ item.record.yellow_cards }} yellow / {{ item.record.red_cards }} red</p></NuxtLink></Card></template></div></template>
