<script setup lang="ts">
import { computed, ref } from 'vue'
import type { AdminGame, GamePlayer } from '@@/types/admin-club'
definePageMeta({ allowedRoles: ['admin'] })
const id = useRoute().params.id as string
const { data, pending, refresh } = await useFetch<{ game: AdminGame, players: GamePlayer[] }>(`/api/admin/games/${id}`)
const selectedIds = ref<string[]>([])
const adding = ref(false)
const { data: eligibleData } = await useFetch<{ players: Array<{ id: string, full_name: string, shirt_number: number | null }> }>(`/api/admin/games/${id}/eligible-players`, { default: () => ({ players: [] }) })
const selectedPlayerIds = computed(() => new Set(data.value?.players.map((player) => player.player_id) ?? []))
async function addPlayers() { adding.value = true; try { await $fetch(`/api/admin/games/${id}/players`, { method: 'POST', body: { player_ids: selectedIds.value } }); selectedIds.value = []; await refresh() } finally { adding.value = false } }
function format(value: string) { return new Intl.DateTimeFormat('en-GB', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value)) }
</script>
<template><div class="mx-auto max-w-4xl space-y-6"><NuxtLink to="/admin/games" class="text-sm text-brand-700">← Games</NuxtLink><div v-if="pending">Loading game...</div><template v-else-if="data"><div><h1>{{ data.game.team.name }} vs {{ data.game.opponent_name }}</h1><p class="text-body text-[color:var(--color-text-secondary)]">{{ format(data.game.scheduled_at) }} · {{ data.game.season.name }}{{ data.game.competition ? ` · ${data.game.competition.name}` : '' }}</p></div><Card class="space-y-2"><p><span class="text-[color:var(--color-text-secondary)]">Venue:</span> {{ data.game.venue?.name || 'To be confirmed' }}</p><p><span class="text-[color:var(--color-text-secondary)]">Status:</span> {{ data.game.status }}</p><p v-if="data.game.status === 'completed'" class="text-h2">{{ data.game.home_score }}–{{ data.game.away_score }}</p></Card><Card class="space-y-3"><h2>Add players</h2><div class="grid gap-2 sm:grid-cols-2"><label v-for="player in eligibleData?.players.filter((item) => !selectedPlayerIds.has(item.id))" :key="player.id" class="flex min-h-[44px] items-center gap-3 rounded-lg border border-border px-3"><input v-model="selectedIds" type="checkbox" :value="player.id">{{ player.full_name }}{{ player.shirt_number ? ` · #${player.shirt_number}` : '' }}</label></div><Button :disabled="adding || !selectedIds.length" @click="addPlayers">{{ adding ? 'Adding...' : 'Add selected players' }}</Button></Card><Card class="overflow-hidden p-0"><div class="border-b border-border p-4"><h2>Squad availability</h2></div><p v-if="!data.players.length" class="p-6 text-center text-sm text-[color:var(--color-text-secondary)]">No players have been added to this game.</p><NuxtLink v-for="player in data.players" :key="player.player_id" :to="`/admin/players/${player.player_id}`" class="flex items-center justify-between gap-3 border-b border-border p-4 last:border-b-0 hover:bg-brand-50/50"><div><p class="font-medium">{{ player.player.full_name }}</p><p class="text-sm text-[color:var(--color-text-secondary)]">{{ player.minutes_played }} min · {{ player.goals }} goals · {{ player.assists }} assists</p></div><Badge :status="player.availability_status === 'available' ? 'confirmed' : player.availability_status === 'unavailable' ? 'declined' : 'pending'">{{ player.availability_status }}</Badge></NuxtLink></Card></template></div></template>
