<script setup lang="ts">
import { computed, ref } from 'vue'
import type { GamePlayer } from '@@/types/admin-club'
definePageMeta({ allowedRoles: ['coach'] })
const gameId = useRoute().params.id as string
const selectedIds = ref<string[]>([]); const saving = ref(false); const error = ref<string | null>(null)
const { data: rosterData, refresh } = await useFetch<{ players: GamePlayer[] }>(`/api/coach/games/${gameId}/players`, { default: () => ({ players: [] }) })
const { data: eligibleData } = await useFetch<{ players: Array<{ id: string, full_name: string }> }>(`/api/coach/games/${gameId}/eligible-players`, { default: () => ({ players: [] }) })
const roster = computed(() => rosterData.value?.players ?? []); const selected = computed(() => new Set(roster.value.map((item) => item.player_id)))
async function addPlayers() { saving.value = true; error.value = null; try { await $fetch(`/api/coach/games/${gameId}/players`, { method: 'POST', body: { player_ids: selectedIds.value } }); selectedIds.value = []; await refresh() } catch (value) { error.value = (value as { data?: { statusMessage?: string } }).data?.statusMessage || 'Unable to add players.' } finally { saving.value = false } }
async function save(player: GamePlayer) { saving.value = true; try { await $fetch(`/api/coach/games/${gameId}/players/${player.player_id}`, { method: 'PATCH', body: { selection_status: player.selection_status, participated: player.participated, minutes_played: player.minutes_played, goals: player.goals, assists: player.assists, yellow_cards: player.yellow_cards, red_cards: player.red_cards, coach_note: player.coach_note } }); await refresh() } catch (value) { error.value = (value as { data?: { statusMessage?: string } }).data?.statusMessage || 'Unable to update player.' } finally { saving.value = false } }
</script>
<template>
  <div class="mx-auto max-w-4xl space-y-6"><NuxtLink to="/coach/games" class="text-sm text-brand-700">← All games</NuxtLink><h1>Game squad</h1><p v-if="error" class="rounded-lg bg-[var(--status-declined-bg)] p-3 text-sm text-[var(--status-declined-text)]">{{ error }}</p><Card class="space-y-4"><h2>Add players</h2><div class="grid gap-2 sm:grid-cols-2"><label v-for="player in eligibleData?.players.filter((item) => !selected.has(item.id))" :key="player.id" class="flex min-h-[44px] items-center gap-3 rounded-lg border border-border px-3"><input v-model="selectedIds" type="checkbox" :value="player.id">{{ player.full_name }}</label></div><Button :disabled="saving || !selectedIds.length" @click="addPlayers">Add selected players</Button></Card><Card class="overflow-hidden p-0"><div class="border-b border-border p-4"><h2>Availability and statistics</h2></div><div v-for="player in roster" :key="player.player_id" class="space-y-3 border-b border-border p-4 last:border-b-0"><div class="flex items-center justify-between gap-3"><p class="font-medium">{{ player.player.full_name }}</p><Badge :status="player.availability_status === 'available' ? 'confirmed' : player.availability_status === 'unavailable' ? 'declined' : 'pending'">{{ player.availability_status }}</Badge></div><p v-if="player.availability_note" class="text-sm text-[color:var(--color-text-secondary)]">Parent note: {{ player.availability_note }}</p><div class="grid gap-3 sm:grid-cols-4"><select v-model="player.selection_status" class="min-h-[40px] rounded-lg border border-input px-2 text-sm"><option value="selected">Selected</option><option value="started">Started</option><option value="substitute">Substitute</option><option value="not_selected">Not selected</option></select><label class="flex items-center gap-2 text-sm"><input v-model="player.participated" type="checkbox">Played</label><Input v-model="player.minutes_played" type="number" min="0" placeholder="Minutes" /><Input v-model="player.goals" type="number" min="0" placeholder="Goals" /><Input v-model="player.assists" type="number" min="0" placeholder="Assists" /><Input v-model="player.yellow_cards" type="number" min="0" max="2" placeholder="Yellow" /><Input v-model="player.red_cards" type="number" min="0" max="1" placeholder="Red" /></div><Button size="sm" variant="outline" :disabled="saving" @click="save(player)">Save player record</Button></div></Card></div>
</template>
