<script setup lang="ts">
import { computed } from 'vue'
import { CalendarClock, ExternalLink, MapPin } from 'lucide-vue-next'
import type { AdminTrainingSession } from '@@/types/admin-club'
import type { MatchWeatherResult } from '@@/types/weather'
definePageMeta({ allowedRoles: ['admin', 'coach', 'parent'] })
const id = useRoute().params.id as string
const { data, pending, error } = await useFetch<{ training: AdminTrainingSession, weather: MatchWeatherResult, weatherAttribution: { label: string, url: string } }>(`/api/coach/calendar/trainings/${id}`)
const training = computed(() => data.value?.training)
const mapsUrl = computed(() => { const venue = training.value?.venue; const query = [venue?.name, venue?.address, venue?.city].filter(Boolean).join(', '); return query ? `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(query)}` : null })
function dateTime(value: string) { return new Intl.DateTimeFormat('pl-PL', { weekday: 'long', day: 'numeric', month: 'long', year: 'numeric', hour: '2-digit', minute: '2-digit' }).format(new Date(value)) }
function endTime(value: string, duration: number) { return new Intl.DateTimeFormat('pl-PL', { hour: '2-digit', minute: '2-digit' }).format(new Date(new Date(value).getTime() + duration * 60_000)) }
</script>
<template><div class="mx-auto max-w-4xl space-y-6"><NuxtLink to="/coach/calendar" class="inline-flex min-h-11 items-center rounded-lg border border-input px-3 text-sm font-medium text-brand-700">← Wróć do kalendarza</NuxtLink><p v-if="pending" class="text-sm">Wczytywanie treningu...</p><p v-else-if="error || !training" class="rounded-lg bg-[var(--status-declined-bg)] p-4 text-sm">{{ error?.statusMessage || 'Nie udało się wczytać treningu.' }}</p><template v-else><div class="space-y-2"><p class="eyebrow text-brand-700">Trening</p><h1>{{ training.team.name }}</h1><p class="flex items-center gap-2 text-body text-[color:var(--color-text-secondary)]"><CalendarClock class="h-4 w-4" />{{ dateTime(training.scheduled_at) }}</p></div><Card class="grid gap-4 sm:grid-cols-2"><div><p class="text-label text-[color:var(--color-text-secondary)]">Czas</p><p>{{ dateTime(training.scheduled_at) }}</p></div><div><p class="text-label text-[color:var(--color-text-secondary)]">Koniec</p><p>{{ endTime(training.scheduled_at, training.duration_minutes) }} · {{ training.duration_minutes }} min</p></div></Card><Card class="space-y-3"><div class="flex gap-3"><MapPin class="mt-0.5 h-5 w-5 text-brand-700" /><div><p class="text-label text-[color:var(--color-text-secondary)]">Miejsce</p><p class="font-medium">{{ training.venue?.name || 'Miejsce do potwierdzenia' }}</p><p v-if="training.venue?.address || training.venue?.city" class="text-sm text-[color:var(--color-text-secondary)]">{{ [training.venue?.address, training.venue?.city].filter(Boolean).join(', ') }}</p></div></div><a v-if="mapsUrl" :href="mapsUrl" target="_blank" rel="noopener noreferrer" class="inline-flex min-h-11 items-center gap-2 rounded-lg border border-input px-3 text-sm text-brand-700"><ExternalLink class="h-4 w-4" />Otwórz w Mapach Google</a></Card><AppMatchWeatherCard v-if="data?.weather.status === 'available'" :weather="data.weather" :attribution="data.weatherAttribution" /><Card v-else-if="data?.weather.status === 'forecast-not-available-yet'" class="text-sm text-[color:var(--color-text-secondary)]">Prognoza pogody nie jest jeszcze dostępna.</Card></template></div></template>
