<script setup lang="ts">
import { ref } from 'vue'
import { useAppAuth } from '@@/composables/useAppAuth'
import { usePolishLocale } from '@@/composables/usePolishLocale'
import type { AvailabilityStatus, GameLocationType } from '@@/types/admin-club'
import type { MatchWeatherResult } from '@@/types/weather'
definePageMeta({ allowedRoles: ['admin', 'parent', 'coach'] })
const { role } = useAppAuth(); const { dateTime, availabilityLabel, locationLabel } = usePolishLocale(); const savingId = ref<string | null>(null)
const { data, refresh } = await useFetch<{ games: Array<{ game_id: string, player_id: string, availability_status: AvailabilityStatus, player: { full_name: string }, game: { opponent_name: string, scheduled_at: string, location_type: GameLocationType, weather?: MatchWeatherResult } }>, weatherAttribution: { label: string, url: string } }>('/api/parent/games', { default: () => ({ games: [], weatherAttribution: { label: 'Weather data by Open-Meteo', url: 'https://open-meteo.com/' } }) })
async function respond(item: { game_id: string, player_id: string }, status: 'available' | 'unavailable') { savingId.value = `${item.game_id}-${item.player_id}`; try { await $fetch(`/api/parent/games/${item.game_id}/players/${item.player_id}/attendance`, { method: 'PATCH', body: { availability_status: status } }); await refresh() } finally { savingId.value = null } }
</script>
<template>
  <div v-if="role === 'admin' || role === 'coach'" class="mx-auto max-w-3xl space-y-4"><h1>Mecze</h1><p class="text-body text-[color:var(--color-text-secondary)]">Skorzystaj z widoku trenera, aby wybierać zawodników i zarządzać dostępnością.</p><Button as="NuxtLink" to="/coach/games">Otwórz mecze trenera</Button></div>
  <div v-else class="mx-auto max-w-3xl space-y-6"><div><h1>Mecze</h1><p class="text-body text-[color:var(--color-text-secondary)]">Potwierdź, czy Twoje dziecko może uczestniczyć w każdym wybranym meczu.</p></div><Card v-if="!data?.games.length" class="text-center text-sm text-[color:var(--color-text-secondary)]">Brak zaproszeń na mecze oczekujących na odpowiedź.</Card><Card v-for="item in data?.games" :key="`${item.game_id}-${item.player_id}`" class="space-y-3"><div><h2>{{ item.game.opponent_name }}</h2><p class="text-sm text-[color:var(--color-text-secondary)]">{{ item.player.full_name }} · {{ dateTime(item.game.scheduled_at) }} · {{ locationLabel(item.game.location_type) }}</p></div><AppMatchWeatherCard v-if="item.game.weather?.status === 'available'" :weather="item.game.weather" :attribution="data!.weatherAttribution" /><p v-else-if="item.game.weather?.status === 'forecast-not-available-yet'" class="text-sm text-[color:var(--color-text-secondary)]">Prognoza pogody nie jest jeszcze dostępna.</p><Badge :status="item.availability_status === 'available' ? 'confirmed' : item.availability_status === 'unavailable' ? 'declined' : 'pending'">{{ availabilityLabel(item.availability_status) }}</Badge><div class="flex gap-3"><Button :disabled="Boolean(savingId)" @click="respond(item, 'available')">Dostępny</Button><Button variant="outline" :disabled="Boolean(savingId)" @click="respond(item, 'unavailable')">Niedostępny</Button></div></Card></div>
</template>
