-- Remove the questions currently listed in 20260904170000_add_quiz_questions.sql
-- from future quiz draws. Keep the records because quiz_session_questions uses
-- ON DELETE RESTRICT and past answers are needed for session/leaderboard history.
-- Questions already presented can still be answered normally.
-- Match exact question/source pairs, not every question sourced from Wikidata.
update public.quiz_questions as question
set is_active = false
from (values
  ('Który kraj reprezentuje lub reprezentował Álvaro Negredo?', 'https://www.wikidata.org/wiki/Q210916'),
  ('Który kraj reprezentuje lub reprezentował Ałan Dzagojew?', 'https://www.wikidata.org/wiki/Q20469'),
  ('Który kraj reprezentuje lub reprezentował Christian Panucci?', 'https://www.wikidata.org/wiki/Q168287'),
  ('Który kraj reprezentuje lub reprezentował Thomas Hitzlsperger?', 'https://www.wikidata.org/wiki/Q57152'),
  ('Który kraj reprezentuje lub reprezentował Henrik Larsson?', 'https://www.wikidata.org/wiki/Q179334'),
  ('Który kraj reprezentuje lub reprezentował Niko Kranjčar?', 'https://www.wikidata.org/wiki/Q84272'),
  ('Który kraj reprezentuje lub reprezentował Jonny Evans?', 'https://www.wikidata.org/wiki/Q29495'),
  ('Który kraj reprezentuje lub reprezentował Deco?', 'https://www.wikidata.org/wiki/Q659634'),
  ('Który kraj reprezentuje lub reprezentował Klaas-Jan Huntelaar?', 'https://www.wikidata.org/wiki/Q26069'),
  ('Który kraj reprezentuje lub reprezentował Adriano Leite Ribeiro?', 'https://www.wikidata.org/wiki/Q170452'),
  ('Który kraj reprezentuje lub reprezentował Sergio Romero?', 'https://www.wikidata.org/wiki/Q215463'),
  ('Który kraj reprezentuje lub reprezentował Jürgen Kohler?', 'https://www.wikidata.org/wiki/Q308925'),
  ('Który kraj reprezentuje lub reprezentował Darren Fletcher?', 'https://www.wikidata.org/wiki/Q172792'),
  ('Który kraj reprezentuje lub reprezentował Jérémy Ménez?', 'https://www.wikidata.org/wiki/Q1923'),
  ('Który kraj reprezentuje lub reprezentował Daniel van Buyten?', 'https://www.wikidata.org/wiki/Q44309'),
  ('Który kraj reprezentuje lub reprezentował Samuel Umtiti?', 'https://www.wikidata.org/wiki/Q13308'),
  ('Który kraj reprezentuje lub reprezentował Éver Banega?', 'https://www.wikidata.org/wiki/Q19392'),
  ('Który kraj reprezentuje lub reprezentował Emre Belözoğlu?', 'https://www.wikidata.org/wiki/Q202569'),
  ('Który kraj reprezentuje lub reprezentował Claudio Caniggia?', 'https://www.wikidata.org/wiki/Q270890'),
  ('Który kraj reprezentuje lub reprezentował Gilberto Silva?', 'https://www.wikidata.org/wiki/Q190142'),
  ('Który kraj reprezentuje lub reprezentował Rüştü Reçber?', 'https://www.wikidata.org/wiki/Q201900'),
  ('Który kraj reprezentuje lub reprezentował Ali Daei?', 'https://www.wikidata.org/wiki/Q159622'),
  ('Który kraj reprezentuje lub reprezentował Enner Valencia?', 'https://www.wikidata.org/wiki/Q2843080'),
  ('Który kraj reprezentuje lub reprezentował Riyad Mahrez?', 'https://www.wikidata.org/wiki/Q8338725'),
  ('Który kraj reprezentuje lub reprezentował Hiroshi Nanami?', 'https://www.wikidata.org/wiki/Q1208375'),
  ('Który kraj reprezentuje lub reprezentował Sol Campbell?', 'https://www.wikidata.org/wiki/Q214734'),
  ('Który kraj reprezentuje lub reprezentował Martín Cáceres?', 'https://www.wikidata.org/wiki/Q194107'),
  ('W którym roku urodził się Steven Pienaar?', 'https://www.wikidata.org/wiki/Q193488'),
  ('W którym roku urodził się Fabio Cannavaro?', 'https://www.wikidata.org/wiki/Q102027'),
  ('W którym roku urodził się Riyad Mahrez?', 'https://www.wikidata.org/wiki/Q8338725'),
  ('W którym roku urodził się Emre Belözoğlu?', 'https://www.wikidata.org/wiki/Q202569'),
  ('W którym roku urodził się Seigō Narazaki?', 'https://www.wikidata.org/wiki/Q331963'),
  ('W którym roku urodził się Yūki Ōtsu?', 'https://www.wikidata.org/wiki/Q509079'),
  ('W którym roku urodził się Dino Zoff?', 'https://www.wikidata.org/wiki/Q180661'),
  ('W którym roku urodził się Keylor Navas?', 'https://www.wikidata.org/wiki/Q969423'),
  ('W którym roku urodził się Masashi Ōguro?', 'https://www.wikidata.org/wiki/Q359749'),
  ('W którym roku urodził się Diego Simeone?', 'https://www.wikidata.org/wiki/Q258115'),
  ('W którym roku urodził się Niko Kovač?', 'https://www.wikidata.org/wiki/Q154305'),
  ('W którym roku urodził się Miloš Krasić?', 'https://www.wikidata.org/wiki/Q201910'),
  ('W którym roku urodził się Angelos Charisteas?', 'https://www.wikidata.org/wiki/Q109417'),
  ('W którym roku urodził się Lucas Neill?', 'https://www.wikidata.org/wiki/Q215358'),
  ('W którym roku urodził się James Milner?', 'https://www.wikidata.org/wiki/Q191136'),
  ('W którym roku urodził się Thomas Vermaelen?', 'https://www.wikidata.org/wiki/Q184177'),
  ('W którym roku urodził się Marc Overmars?', 'https://www.wikidata.org/wiki/Q219248'),
  ('W którym roku urodził się Cafu?', 'https://www.wikidata.org/wiki/Q178683'),
  ('W którym roku urodził się Ibrahim Afellay?', 'https://www.wikidata.org/wiki/Q165014'),
  ('W którym roku urodził się Claudio Caniggia?', 'https://www.wikidata.org/wiki/Q270890'),
  ('W którym roku urodził się Esteban Cambiasso?', 'https://www.wikidata.org/wiki/Q192122'),
  ('W którym roku urodził się John Obi Mikel?', 'https://www.wikidata.org/wiki/Q166984'),
  ('W którym roku urodził się Javier Mascherano?', 'https://www.wikidata.org/wiki/Q161571'),
  ('W którym roku urodził się Dimitri Payet?', 'https://www.wikidata.org/wiki/Q376247'),
  ('W którym roku urodził się Miroslav Klose?', 'https://www.wikidata.org/wiki/Q80471'),
  ('W którym roku urodził się Jari Litmanen?', 'https://www.wikidata.org/wiki/Q209650'),
  ('W którym roku urodził się Paulo Wanchope?', 'https://www.wikidata.org/wiki/Q211126'),
  ('W którym roku urodził się Ángel Di María?', 'https://www.wikidata.org/wiki/Q251683'),
  ('W którym roku urodził się Jordan Ayew?', 'https://www.wikidata.org/wiki/Q367861'),
  ('W którym roku urodził się Frank de Boer?', 'https://www.wikidata.org/wiki/Q219657'),
  ('W którym roku urodził się Teddy Sheringham?', 'https://www.wikidata.org/wiki/Q234576'),
  ('W którym roku urodził się Toshihiro Hattori?', 'https://www.wikidata.org/wiki/Q495803'),
  ('W którym roku urodził się Leroy Sané?', 'https://www.wikidata.org/wiki/Q16499882'),
  ('W którym roku urodził się Sylvain Wiltord?', 'https://www.wikidata.org/wiki/Q217760'),
  ('W którym roku urodził się Bastian Schweinsteiger?', 'https://www.wikidata.org/wiki/Q44298'),
  ('W którym roku urodził się Gary Neville?', 'https://www.wikidata.org/wiki/Q348857'),
  ('W którym roku urodził się David Villa?', 'https://www.wikidata.org/wiki/Q83006'),
  ('W którym roku urodził się Jérémy Toulalan?', 'https://www.wikidata.org/wiki/Q1944'),
  ('W jakim mieście lub miejscowości urodził się Frank de Boer?', 'https://www.wikidata.org/wiki/Q219657'),
  ('W jakim mieście lub miejscowości urodził się Davor Šuker?', 'https://www.wikidata.org/wiki/Q189217'),
  ('W jakim mieście lub miejscowości urodził się Niko Kranjčar?', 'https://www.wikidata.org/wiki/Q84272'),
  ('W jakim mieście lub miejscowości urodził się Giovanni van Bronckhorst?', 'https://www.wikidata.org/wiki/Q173360'),
  ('W jakim mieście lub miejscowości urodził się Gilberto Silva?', 'https://www.wikidata.org/wiki/Q190142'),
  ('W jakim mieście lub miejscowości urodził się Berti Vogts?', 'https://www.wikidata.org/wiki/Q828203'),
  ('W jakim mieście lub miejscowości urodził się Jan Vertonghen?', 'https://www.wikidata.org/wiki/Q313170'),
  ('W jakim mieście lub miejscowości urodził się Nemanja Matić?', 'https://www.wikidata.org/wiki/Q297603'),
  ('W jakim mieście lub miejscowości urodził się Djibril Cissé?', 'https://www.wikidata.org/wiki/Q1936'),
  ('W jakim mieście lub miejscowości urodził się Luiz Gustavo?', 'https://www.wikidata.org/wiki/Q329451'),
  ('W jakim mieście lub miejscowości urodził się Makoto Hasebe?', 'https://www.wikidata.org/wiki/Q164676'),
  ('W jakim mieście lub miejscowości urodził się Claudio Pizarro?', 'https://www.wikidata.org/wiki/Q109397'),
  ('W jakim mieście lub miejscowości urodził się Yohan Cabaye?', 'https://www.wikidata.org/wiki/Q1910'),
  ('W jakim mieście lub miejscowości urodził się Romário?', 'https://www.wikidata.org/wiki/Q178649'),
  ('W jakim mieście lub miejscowości urodził się Joan Capdevila?', 'https://www.wikidata.org/wiki/Q188793'),
  ('W jakim mieście lub miejscowości urodził się Łukasz Fabiański?', 'https://www.wikidata.org/wiki/Q40596'),
  ('W jakim mieście lub miejscowości urodził się Víctor Valdés?', 'https://www.wikidata.org/wiki/Q47548'),
  ('W jakim mieście lub miejscowości urodził się Darwin Núñez?', 'https://www.wikidata.org/wiki/Q46372260'),
  ('W jakim mieście lub miejscowości urodził się Raúl González Blanco?', 'https://www.wikidata.org/wiki/Q11576'),
  ('W jakim mieście lub miejscowości urodził się Manuel Neuer?', 'https://www.wikidata.org/wiki/Q107365'),
  ('W jakim mieście lub miejscowości urodził się Robin van Persie?', 'https://www.wikidata.org/wiki/Q2339'),
  ('W jakim mieście lub miejscowości urodził się Alessandro Del Piero?', 'https://www.wikidata.org/wiki/Q624'),
  ('W jakim mieście lub miejscowości urodził się Edin Džeko?', 'https://www.wikidata.org/wiki/Q153786'),
  ('W jakim mieście lub miejscowości urodził się Martín Cáceres?', 'https://www.wikidata.org/wiki/Q194107'),
  ('W jakim mieście lub miejscowości urodził się Kazumichi Takagi?', 'https://www.wikidata.org/wiki/Q982151'),
  ('W jakim mieście lub miejscowości urodził się Alessandro Nesta?', 'https://www.wikidata.org/wiki/Q227892'),
  ('W jakim mieście lub miejscowości urodził się Daiki Niwa?', 'https://www.wikidata.org/wiki/Q763939'),
  ('W jakim mieście lub miejscowości urodził się Keita Suzuki?', 'https://www.wikidata.org/wiki/Q558896'),
  ('W jakim mieście lub miejscowości urodził się Fabio Grosso?', 'https://www.wikidata.org/wiki/Q230529'),
  ('Na jakiej pozycji występował lub występuje Matheus Cunha?', 'https://www.wikidata.org/wiki/Q35831063'),
  ('Na jakiej pozycji występował lub występuje Seigō Narazaki?', 'https://www.wikidata.org/wiki/Q331963'),
  ('Na jakiej pozycji występował lub występuje Emmanuel Adebayor?', 'https://www.wikidata.org/wiki/Q386876'),
  ('Na jakiej pozycji występował lub występuje Niko Kranjčar?', 'https://www.wikidata.org/wiki/Q84272'),
  ('Na jakiej pozycji występował lub występuje Wynton Rufer?', 'https://www.wikidata.org/wiki/Q124043'),
  ('Na jakiej pozycji występował lub występuje John Heitinga?', 'https://www.wikidata.org/wiki/Q946457'),
  ('Na jakiej pozycji występował lub występuje Gabriel Heinze?', 'https://www.wikidata.org/wiki/Q63659'),
  ('Na jakiej pozycji występował lub występuje Park Ji-sung?', 'https://www.wikidata.org/wiki/Q50603'),
  ('Na jakiej pozycji występował lub występuje Takayuki Morimoto?', 'https://www.wikidata.org/wiki/Q310602'),
  ('Na jakiej pozycji występował lub występuje Gervinho?', 'https://www.wikidata.org/wiki/Q208025'),
  ('Na jakiej pozycji występował lub występuje Paul Scholes?', 'https://www.wikidata.org/wiki/Q45613'),
  ('Na jakiej pozycji występował lub występuje Shunsuke Nakamura?', 'https://www.wikidata.org/wiki/Q191138'),
  ('Na jakiej pozycji występował lub występuje Éric Maxim Choupo-Moting?', 'https://www.wikidata.org/wiki/Q309532'),
  ('Na jakiej pozycji występował lub występuje Gaël Clichy?', 'https://www.wikidata.org/wiki/Q1929'),
  ('Na jakiej pozycji występował lub występuje Shū Kurata?', 'https://www.wikidata.org/wiki/Q210117'),
  ('Na jakiej pozycji występował lub występuje Luke Shaw?', 'https://www.wikidata.org/wiki/Q93563'),
  ('Na jakiej pozycji występował lub występuje Sokratis Papastatopulos?', 'https://www.wikidata.org/wiki/Q192923'),
  ('Na jakiej pozycji występował lub występuje Robinho?', 'https://www.wikidata.org/wiki/Q58441'),
  ('Na jakiej pozycji występował lub występuje Mark van Bommel?', 'https://www.wikidata.org/wiki/Q151853'),
  ('Na jakiej pozycji występował lub występuje Eduardo da Silva?', 'https://www.wikidata.org/wiki/Q180444'),
  ('Na jakiej pozycji występował lub występuje Javier Pastore?', 'https://www.wikidata.org/wiki/Q276434'),
  ('W jakim kraju ma siedzibę klub CD Lugo?', 'https://www.wikidata.org/wiki/Q11984'),
  ('W jakim kraju ma siedzibę klub Ebbsfleet United F.C.?', 'https://www.wikidata.org/wiki/Q18511'),
  ('W jakim kraju ma siedzibę klub CA Osasuna?', 'https://www.wikidata.org/wiki/Q10286'),
  ('W jakim kraju ma siedzibę klub Portsmouth F.C.?', 'https://www.wikidata.org/wiki/Q19604'),
  ('W jakim kraju ma siedzibę klub Bolton Wanderers F.C.?', 'https://www.wikidata.org/wiki/Q19451'),
  ('W jakim kraju ma siedzibę klub FC United of Manchester?', 'https://www.wikidata.org/wiki/Q18274'),
  ('W jakim kraju ma siedzibę klub 1. FC Kaiserslautern?', 'https://www.wikidata.org/wiki/Q8466'),
  ('W jakim kraju ma siedzibę klub West Bromwich Albion F.C.?', 'https://www.wikidata.org/wiki/Q18744'),
  ('W jakim kraju ma siedzibę klub Dinamo Moskwa?', 'https://www.wikidata.org/wiki/Q17497'),
  ('W jakim kraju ma siedzibę klub Getafe CF?', 'https://www.wikidata.org/wiki/Q8806'),
  ('W jakim kraju ma siedzibę klub ND Triglav Kranj?', 'https://www.wikidata.org/wiki/Q44308'),
  ('W jakim kraju ma siedzibę klub Hellas Verona?', 'https://www.wikidata.org/wiki/Q8639'),
  ('W jakim kraju ma siedzibę klub FC Sochaux-Montbéliard?', 'https://www.wikidata.org/wiki/Q19512'),
  ('W jakim kraju ma siedzibę klub West Ham United F.C.?', 'https://www.wikidata.org/wiki/Q18747'),
  ('W jakim kraju ma siedzibę klub Dinamo Tirana?', 'https://www.wikidata.org/wiki/Q34120'),
  ('W jakim kraju ma siedzibę klub Real Sociedad?', 'https://www.wikidata.org/wiki/Q10315'),
  ('W jakim kraju ma siedzibę klub FK Senica?', 'https://www.wikidata.org/wiki/Q19384'),
  ('W jakim kraju ma siedzibę klub ACR Siena 1904?', 'https://www.wikidata.org/wiki/Q2756'),
  ('W jakim kraju ma siedzibę klub Doncaster Rovers F.C.?', 'https://www.wikidata.org/wiki/Q19589'),
  ('W jakim kraju ma siedzibę klub Brentford F.C.?', 'https://www.wikidata.org/wiki/Q19571'),
  ('W jakim kraju ma siedzibę klub Sampdoria Genua?', 'https://www.wikidata.org/wiki/Q1457'),
  ('W jakim kraju ma siedzibę klub Hartlepool United F.C.?', 'https://www.wikidata.org/wiki/Q19592'),
  ('W jakim kraju ma siedzibę klub Colchester United F.C.?', 'https://www.wikidata.org/wiki/Q19578'),
  ('W jakim kraju ma siedzibę klub Preston North End F.C.?', 'https://www.wikidata.org/wiki/Q19612'),
  ('W jakim kraju ma siedzibę klub Charlton Athletic F.C.?', 'https://www.wikidata.org/wiki/Q19462'),
  ('W jakim kraju ma siedzibę klub Corporación Deportiva Once Caldas?', 'https://www.wikidata.org/wiki/Q47533'),
  ('W jakim kraju ma siedzibę klub Huddersfield Town F.C.?', 'https://www.wikidata.org/wiki/Q19473'),
  ('W którym roku założono klub AS Bari?', 'https://www.wikidata.org/wiki/Q6641'),
  ('W którym roku założono klub Tamworth F.C.?', 'https://www.wikidata.org/wiki/Q18527'),
  ('W którym roku założono klub Gateshead F.C.?', 'https://www.wikidata.org/wiki/Q18513'),
  ('W którym roku założono klub VfB Stuttgart?', 'https://www.wikidata.org/wiki/Q4512'),
  ('W którym roku założono klub Scunthorpe United F.C.?', 'https://www.wikidata.org/wiki/Q19615'),
  ('W którym roku założono klub Dinamo Moskwa?', 'https://www.wikidata.org/wiki/Q17497'),
  ('W którym roku założono klub Bayern Monachium?', 'https://www.wikidata.org/wiki/Q15789'),
  ('W którym roku założono klub Leicester City?', 'https://www.wikidata.org/wiki/Q19481'),
  ('W którym roku założono klub Atlético Madryt?', 'https://www.wikidata.org/wiki/Q8701'),
  ('W którym roku założono klub Luton Town F.C.?', 'https://www.wikidata.org/wiki/Q18520'),
  ('W którym roku założono klub FC United of Manchester?', 'https://www.wikidata.org/wiki/Q18274'),
  ('W którym roku założono klub CD Mirandés?', 'https://www.wikidata.org/wiki/Q11997'),
  ('W którym roku założono klub RCD Mallorca?', 'https://www.wikidata.org/wiki/Q8835'),
  ('W którym roku założono klub Stoke City F.C.?', 'https://www.wikidata.org/wiki/Q18736'),
  ('W którym roku założono klub Ternana Calcio?', 'https://www.wikidata.org/wiki/Q8623'),
  ('W którym roku założono klub SS Juve Stabia?', 'https://www.wikidata.org/wiki/Q6748'),
  ('W którym roku założono klub Bolton Wanderers F.C.?', 'https://www.wikidata.org/wiki/Q19451'),
  ('W którym roku założono klub Norwich City F.C.?', 'https://www.wikidata.org/wiki/Q18721'),
  ('W którym roku założono klub Skënderbeu Korcza?', 'https://www.wikidata.org/wiki/Q73996'),
  ('W jakim mieście lub jednostce administracyjnej znajduje się stadion Oracle Park?', 'https://www.wikidata.org/wiki/Q298585'),
  ('W jakim mieście lub jednostce administracyjnej znajduje się stadion Volksparkstadion?', 'https://www.wikidata.org/wiki/Q150933'),
  ('W jakim mieście lub jednostce administracyjnej znajduje się stadion Qinhuangdao Olympic Sports Center Stadium?', 'https://www.wikidata.org/wiki/Q851446'),
  ('W jakim mieście lub jednostce administracyjnej znajduje się stadion Estadio Cuauhtémoc?', 'https://www.wikidata.org/wiki/Q124769'),
  ('W jakim mieście lub jednostce administracyjnej znajduje się stadion Turf Moor?', 'https://www.wikidata.org/wiki/Q683112'),
  ('W jakim mieście lub jednostce administracyjnej znajduje się stadion Estádio do Bessa?', 'https://www.wikidata.org/wiki/Q1058494'),
  ('W jakim mieście lub jednostce administracyjnej znajduje się stadion Ricoh Arena?', 'https://www.wikidata.org/wiki/Q842077'),
  ('W jakim mieście lub jednostce administracyjnej znajduje się stadion Estadio La Rosaleda?', 'https://www.wikidata.org/wiki/Q695879'),
  ('W jakim mieście lub jednostce administracyjnej znajduje się stadion Carrow Road?', 'https://www.wikidata.org/wiki/Q123017'),
  ('W jakim mieście lub jednostce administracyjnej znajduje się stadion Sydney Football Stadium?', 'https://www.wikidata.org/wiki/Q1053447')
) as removed(question, source_url)
where question.question = removed.question
  and question.source_url = removed.source_url
  and question.is_active;
